## Spring Boot App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atsonhome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atsonhome
  template:
    metadata:
      name: atsonhome
      labels:
        app: atsonhome
    spec:
      containers:
      - name: springappcontainer
        image: dhananjayshelke/atson-corp-homepage:latest
        ports:
        - containerPort: 8080
